# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
            Symfony\Component\Security\Core\User\User: 
                algorithm: bcrypt
                cost: 12

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: 
                users:
                    sciAdmin:
                        password: $2y$12$ATdc9PMnYxtR/EPq/bnN..dtyygfGYXaXxznqL8iF1QSocgyupLM2
                        roles: 'ROLE_ADMIN'
                        #$2y$12$R0brO4OWJpIQ.b2V9VQ43uRWhm1e0/UqR0NIvD.ggYkjvHNfNG1RW 
                        #e=mc2

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            form_login:
                login_path: app_login
                check_path: app_login

            # Active le logout (ne fonctionne pas avec http_basic)
            logout:
                path:   /logout
                target: app_login

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }