app_admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

app_home:
    path: /
    defaults: { _controller: AppBundle:App:home }

app_publication:
    path: /publication/{publicationId}
    defaults: { _controller: AppBundle:App:publication }

app_science:
    path: /sciences/{scienceId}
    defaults: { _controller: AppBundle:App:science }

app_sciences:
    path: /sciences
    defaults: { _controller: AppBundle:App:sciences }

app_publish:
    path: /publish
    defaults: { _controller: AppBundle:App:publish }