AppBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
#        publication:
#            type: object
#            nullable: true
        pseudo:
            type: string
            length: '64'
        message:
            type: text
    manyToOne:
        publication:
            targetEntity: AppBundle\Entity\Publication
            joinColum:
                name: publication_id
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
